using SecureMailGateway.Models.Enums;
using System.ComponentModel.DataAnnotations;

namespace SecureMailGateway.Models.Dtos;

public class SendMailRequest
{
    [Required, MaxLength(50)]
    public string ClientCode { get; set; } = string.Empty;

    [Required, MaxLength(50)]
    public string TemplateCode { get; set; } = string.Empty;

    [Required, MinLength(1)]
    public List<string> To { get; set; } = [];

    public List<string>? Cc { get; set; }
    public List<string>? Bcc { get; set; }

    public Dictionary<string, string>? SubjectData { get; set; }
    public Dictionary<string, string>? BodyData { get; set; }

    public List<MailAttachmentDto>? Attachments { get; set; }

    public EmailPriority Priority { get; set; } = EmailPriority.Normal;

    [MaxLength(500), Url]
    public string? CallbackUrl { get; set; }
}

public class MailAttachmentDto
{
    [Required, MaxLength(255)]
    public string FileName { get; set; } = string.Empty;

    [Required, MaxLength(100)]
    public string ContentType { get; set; } = "application/octet-stream";

    [Required]
    public string Base64Content { get; set; } = string.Empty;
}

public class SendMailResponse
{
    public bool Success { get; set; }
    public string? MailCode { get; set; }
    public Guid? TrackingId { get; set; }
    public string? Status { get; set; }
    public string? Error { get; set; }
}

public class MailStatusResponse
{
    public string MailCode { get; set; } = string.Empty;
    public Guid TrackingId { get; set; }
    public string Status { get; set; } = string.Empty;
    public string? TemplateCode { get; set; }
    public string Subject { get; set; } = string.Empty;
    public List<string> To { get; set; } = [];
    public DateTimeOffset QueuedAt { get; set; }
    public DateTimeOffset? SendingAt { get; set; }
    public DateTimeOffset? SentAt { get; set; }
    public DateTimeOffset? FailedAt { get; set; }
    public string? ErrorMessage { get; set; }
    public string? SmtpResponse { get; set; }
    public List<MailStatusEventDto> Events { get; set; } = [];
}

public class MailStatusEventDto
{
    public string EventType { get; set; } = string.Empty;
    public string? Message { get; set; }
    public DateTimeOffset CreatedAt { get; set; }
}

public class TemplateInventoryResponse
{
    public int Count { get; set; }
    public List<TemplateInventoryItemDto> Templates { get; set; } = [];

    /// <summary>Codes demandés via ?codes= qui n'existent pas dans le catalogue.</summary>
    public List<string> Missing { get; set; } = [];
}

public class TemplateInventoryItemDto
{
    public string TemplateCode { get; set; } = string.Empty;
    public string Name { get; set; } = string.Empty;
    public string Language { get; set; } = "fr";
    public int Version { get; set; }
    public bool IsActive { get; set; }

    /// <summary>
    /// Template créé implicitement par un premier appel API sur un code inconnu : le contenu
    /// est un texte de remplacement, donc un code marqué ainsi signale une faute de frappe
    /// côté application ou un template jamais rédigé.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    public List<string> RequiredVariables { get; set; } = [];
    public DateTimeOffset UpdatedAt { get; set; }
}
