using SecureMailGateway.Models.Entities;

namespace SecureMailGateway.Data;

/// <summary>
/// Catalogue des définitions seedées (toutes apps) pour résoudre un template
/// sans dépendre uniquement de la base — évite d'envoyer les stubs AUTO.
/// </summary>
public static class EmailTemplateCatalog
{
    private static readonly Lazy<IReadOnlyDictionary<string, EmailTemplateSeed>> ByCodeLang = new(BuildIndex);

    public static EmailTemplateSeed? Find(string templateCode, string language)
    {
        var code = templateCode.Trim().ToUpperInvariant();
        var lang = NormalizeLanguage(language);
        if (ByCodeLang.Value.TryGetValue($"{code}|{lang}", out var exact))
            return exact;
        if (!string.Equals(lang, "fr", StringComparison.OrdinalIgnoreCase)
            && ByCodeLang.Value.TryGetValue($"{code}|fr", out var fr))
            return fr;
        return null;
    }

    public static bool IsAutoGeneratedStub(EmailTemplate entity)
    {
        if (EmailTemplate.IsAutoGeneratedName(entity.Name))
            return true;

        return entity.HtmlBody.Contains("Template auto-cree:", StringComparison.OrdinalIgnoreCase)
               || entity.SubjectTemplate.Contains("] Notification ", StringComparison.OrdinalIgnoreCase);
    }

    public static void ApplySeed(EmailTemplate entity, EmailTemplateSeed seed)
    {
        entity.Name = seed.Name;
        entity.SubjectTemplate = seed.SubjectTemplate;
        entity.HtmlBody = seed.HtmlBody;
        entity.TextBody = seed.TextBody;
        entity.Language = seed.Language;
        entity.IsActive = seed.IsActive;
        entity.Version = entity.Version < 1 ? 1 : entity.Version + 1;
        entity.UpdatedAt = DateTimeOffset.UtcNow;
    }

    public static EmailTemplate ToEntity(EmailTemplateSeed seed) => seed.ToEntity();

    private static IReadOnlyDictionary<string, EmailTemplateSeed> BuildIndex()
    {
        var map = new Dictionary<string, EmailTemplateSeed>(StringComparer.OrdinalIgnoreCase);
        foreach (var definitions in new IReadOnlyList<EmailTemplateSeed>[]
                 {
                     BoutiqueGiseTemplates.Definitions,
                     TutorSphereTemplates.Definitions,
                     HoloTutoTemplates.Definitions,
                     ComptaDocTemplates.Definitions
                 })
        {
            foreach (var definition in definitions)
            {
                var key = $"{definition.TemplateCode.Trim().ToUpperInvariant()}|{NormalizeLanguage(definition.Language)}";
                map[key] = definition;
            }
        }

        return map;
    }

    private static string NormalizeLanguage(string? language)
    {
        if (string.IsNullOrWhiteSpace(language))
            return "fr";
        var trimmed = language.Trim();
        if (trimmed.Equals("zh-hans", StringComparison.OrdinalIgnoreCase)
            || trimmed.Equals("zh-Hans", StringComparison.OrdinalIgnoreCase))
            return "zh-Hans";

        var lower = trimmed.ToLowerInvariant();
        return lower is "fr" or "en" or "es" or "de" or "pt" or "ar"
            ? lower
            : (trimmed.Length <= 10 ? trimmed : "fr");
    }
}
